### PR TITLE
Change logging-level of startup messages

### PR DESCRIPTION
**Pull request by EvModder**
this is a very minor nitpick.

I think the average user doesn't need this level of detail (unless debugging this plugin), this is what is currently shown:
```
[08:50:52 INFO]: [AntiPopup] Loading AntiPopup v4.6
[08:50:52 INFO]: [AntiPopup] Loaded PacketEvents.
...
[08:50:55 INFO]: [AntiPopup] Enabling AntiPopup v4.6
[08:50:56 INFO]: [AntiPopup] Config enabled.
[08:50:56 INFO]: [AntiPopup] Loaded optional metrics.
[08:50:56 INFO]: [AntiPopup] Initiated PacketEvents.
[08:50:56 INFO]: [AntiPopup] Commands registered.
[08:50:56 INFO]: [AntiPopup] Enabled 1.19 ViaVersion Hook.
```

### CODE REVIEW

**Comment by KaspianDev** [comment]
How does it look when changed to "fine"?

**Comment by EvModder** [comment]
There are several logging levels (details [here](https://riptutorial.com/bukkit/example/24054/logging-levels)), but as I understand it, `SEVERE` will show up as red in the console, `WARNING` will show up as yellow, `INFO` uses the default color (and is usually the default logging level), and `FINE` and `TRACE` are usually used for debugging or extra details.

There is a logging config setting (I think it's a Java flag you specify when running a jar, but bukkit/spigot might have a config option for it as well), and the way it works is it will only show messages of an equal or higher level to what you specify. So if you specify `TRACE/FINEST` it will show *everything*, if you specify `WARNING` it will only show `WARNING` and `SEVERE`, etc.

Note: I didn't know about hacktoberfest, but now I do and it looks interesting 😃

**Comment by KaspianDev** [comment]
Okay please make the level a config option, that'd be better I think, you can make fine a default level

PS: keep general info about plugin being enabled and disabled on info.

**Comment by EvModder** [comment]
Ah I see there are merge conflicts; did you get a change to review my PR though?

**Pull request closed without merging**
